keys:
  - &user_chlorodose 676E7ED23DB572106D83619F8727616DB2324794
  - &host_cl-server age1zs4dcmqa2wxt3wx9f5mc9rekskz2cg39dvfv7jhwtef5uw5mpvgqgeurcl
  - &host_cl-laptop age1fxg8u7kflyzdpntrarq0pgytmxhzzjvdzumx8vqwvp2clszfr32scvwyvd
creation_rules:
  - path_regex: secrets/default.yaml
    key_groups:
    - pgp:
      - *user_chlorodose
      age:
      - *host_cl-server
      - *host_cl-laptop
  - path_regex: secrets/services.yaml
    key_groups:
    - pgp:
      - *user_chlorodose
      age:
      - *host_cl-server
  - path_regex: secrets/vpn/*
    key_groups:
    - pgp:
      - *user_chlorodose
      age:
      - *host_cl-server
  - path_regex: secrets/website/*
    key_groups:
    - pgp:
      - *user_chlorodose
      age:
      - *host_cl-server
  - path_regex: secrets/samba/*
    key_groups:
    - pgp:
      - *user_chlorodose
      age:
      - *host_cl-server