keys:
  - &user_chlorodose 676E7ED23DB572106D83619F8727616DB2324794
  - &host_cl-server age18hwaa8day3379dja06ppr5237l0nmt5r9zhwpm8hx03k06w4kqeq0m6jh2
  - &host_cl-laptop age1fxg8u7kflyzdpntrarq0pgytmxhzzjvdzumx8vqwvp2clszfr32scvwyvd
creation_rules:
  - path_regex: secrets/default.yaml
    key_groups:
    - pgp:
      - *user_chlorodose
      age:
      - *host_cl-server
      - *host_cl-laptop