user-passwords:
    root: ENC[AES256_GCM,data:3goeB/gMZk8DEoJP0U+UxLLxhHqOIzrhgDY+JPrVv1trxsmEtjrqDcsSFs2jAkaAEGvykySiK1uaVRvXgVsfcMV9ipKzDAPMfg==,iv:KrmTxzbe/b2IkpL2FufrVL1j6Fhsz3FgteyopkSue2s=,tag:T19onI+PnHZFgQ01KOCOCA==,type:str]
    chlorodose: ENC[AES256_GCM,data:yDMu4dwVjFlh0dqPjNJsvrN4qHiBF7LBVL2aTp6jq0bTSpZv8em8z4k3tBxJ4LflCW9b4dP87QPFwpGprD1j6MNokkDhp2XY+g==,iv:8MTw8iqIqf6hnqfyjsgvU6+cRlFD9Gk73gb4pnTiBS8=,tag:ITfNDih7xt9WOXAzhAW/mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hwaa8day3379dja06ppr5237l0nmt5r9zhwpm8hx03k06w4kqeq0m6jh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUXpVcDlRc0FOc2hGZmx3
            bGZRWXNkcVZHK3g2eTcyNzVQVVVoU3dXT1Y4CkJxdGsrUy84SERvOGU1ZlMxWUhX
            SkNZRUJiMjlmcWtUK1o4TThvZmdSaWcKLS0tIEhtLy9EUWlwV0Vzd1FrRkUvMzc2
            STFLTmhhdU9xaytNdldvWG5ydnEya2cKUqkPM4dpn6gqKw8/qJIsEAYmW8asoS1O
            WJeY4G+KkzEXrnT58Xao5vwrsM1z3Tlp3ddfl5ovg3jmIdT+v0Ysog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fxg8u7kflyzdpntrarq0pgytmxhzzjvdzumx8vqwvp2clszfr32scvwyvd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdTFCV0FvTG94cDM0L1N6
            TkY1d1o3YjlBWVpwRHMwcVVORzJTSnFpN0VnCko2QmJEREphWjNxSzl4alhkUlht
            WFFkTHNpTzF0NTBLckc4TDFJQmFrcU0KLS0tIDJ6ZGp0RnpYb083clZXQ092MlI0
            UjhHMURBTzZqTTBiWFE0c2Q3RWdGMVEKTTMTMkm+YXyAR1HJh66CoKMPmMrREJfl
            9k7USbjHtV4h68Q6f1oP+t+O3Qq8+PaDDbzzWh1DfwVssz7ZxDn7yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T08:07:34Z"
    mac: ENC[AES256_GCM,data:mEBSRqFwfajfAmpLCScwpubDJHcZB3OKfXqqB8bFGE1Dg9etvcfSlOttTuM32KSSQrlCREZSE+TBhG4Mg+nnts86BSIltJAoTjM7jlZYD+nS3NKR1Y6FaTugXAD7SLnXN962DRtKhDMQUr+7sw3qgh+hEeuzvweq3OVqtuP1A/Y=,iv:0JXiGZk+hNdpATeLANrp4ICrgFz3Rh4+05Hg+9c4yJE=,tag:S4FKmzPbbMuwaZI/Ep8psA==,type:str]
    pgp:
        - created_at: "2025-02-14T10:39:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DhydhbbIyR5QSAQdAtL3ytHVLPNfV8uJZkST/TKqWYevsz6d/HdPiGgULSTEw
            GjW21QBMG7YY+Uax1xoPYjeI5AsgnIWVlUJ1rNDtRC7NuH2/irxNF+qZGFhfmeGo
            0l4Bbf6e0ewkPAyuPD4UDeIn90ySfNL715wwSBnVn+wWF570fr3JCLTgpIkvMdgP
            hfkt7Tq1Jt7AEKdplKTXwXpZy19qpsXCDyLbsto6nwZmG1yxR40+53UG2ROPUtOp
            =/x+s
            -----END PGP MESSAGE-----
          fp: 676E7ED23DB572106D83619F8727616DB2324794
    unencrypted_suffix: _unencrypted
    version: 3.9.4
