user-passwords:
    root: ENC[AES256_GCM,data:3goeB/gMZk8DEoJP0U+UxLLxhHqOIzrhgDY+JPrVv1trxsmEtjrqDcsSFs2jAkaAEGvykySiK1uaVRvXgVsfcMV9ipKzDAPMfg==,iv:KrmTxzbe/b2IkpL2FufrVL1j6Fhsz3FgteyopkSue2s=,tag:T19onI+PnHZFgQ01KOCOCA==,type:str]
    chlorodose: ENC[AES256_GCM,data:yDMu4dwVjFlh0dqPjNJsvrN4qHiBF7LBVL2aTp6jq0bTSpZv8em8z4k3tBxJ4LflCW9b4dP87QPFwpGprD1j6MNokkDhp2XY+g==,iv:8MTw8iqIqf6hnqfyjsgvU6+cRlFD9Gk73gb4pnTiBS8=,tag:ITfNDih7xt9WOXAzhAW/mQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs4dcmqa2wxt3wx9f5mc9rekskz2cg39dvfv7jhwtef5uw5mpvgqgeurcl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVkZWa0JJWmhLWWsva0NT
            UGlGa0QxTHpDN3lvMFlJaHJCMnp5TGVIVDB3CkRJVVd5MTNYRms1UlVZeTB0dk8v
            UTZaY0FzTDdieGRvSFF1WncxdFAvOGcKLS0tIHJvci9Sb0tnYUNxK2xUSkhXVG5R
            enAzOVR4YWZWcllXQzIyM1NVem56TFEKzCH4IDlBZK9q8sPEVjhuSFakI0B7KJW3
            aZwLUsN9w/WYwpUTkE69QyA6eCjezf9Hi8TACQXoMxP6XEbp5U367w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fxg8u7kflyzdpntrarq0pgytmxhzzjvdzumx8vqwvp2clszfr32scvwyvd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyakhZMnY4VGNoRzZOWlZa
            WUJ1RGRxRmoyZnFhU3N6OUxHZCtQTVdKYmdRCkhuWTV1OWNNL280am9SaUs5cGcx
            dmp4WUgzK0ZPZmVqUGZRbUpOcUZWblEKLS0tIDBmblBQNnRnZTgyS2ZqQW1jNFBn
            ZUlrYW9FSzBqb2hCdEdmVER1c3JwSUkKcrdOtM38aS12oDcj7v9XjePvD6uTUWHh
            QoKhUiKvcGPjVzl4x3zE78DKxGc7YPHBRt5uaEEVyUIV5xrig34KOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T08:07:34Z"
    mac: ENC[AES256_GCM,data:mEBSRqFwfajfAmpLCScwpubDJHcZB3OKfXqqB8bFGE1Dg9etvcfSlOttTuM32KSSQrlCREZSE+TBhG4Mg+nnts86BSIltJAoTjM7jlZYD+nS3NKR1Y6FaTugXAD7SLnXN962DRtKhDMQUr+7sw3qgh+hEeuzvweq3OVqtuP1A/Y=,iv:0JXiGZk+hNdpATeLANrp4ICrgFz3Rh4+05Hg+9c4yJE=,tag:S4FKmzPbbMuwaZI/Ep8psA==,type:str]
    pgp:
        - created_at: "2025-03-16T12:33:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DhydhbbIyR5QSAQdAd3QBwD0KepFaNTQpxgGwa5LEYBwNRxmWeK0196A1tQ8w
            ZixwGsKVVIV1CO4JssJ13VfZrODhE1GPpAp+FTcWlUSEwSaKd/VLbCaOzzovmqIg
            0l4BVx5xxv2LD5syvzzAdlHdV37uoW318I6w3iFiDTUDKmgXUZCRbKrh0zzvb0nd
            7sFkH05lW5caspeYC3CZn3JiZFyIzLFuMuxN+zMrsrh/RUZDMvMeCnhsl+tHFa/p
            =oOBo
            -----END PGP MESSAGE-----
          fp: 676E7ED23DB572106D83619F8727616DB2324794
    unencrypted_suffix: _unencrypted
    version: 3.9.4
