ppp:
    wan: ENC[AES256_GCM,data:DkaAHMrIcK8Mc5OSxA7nQNr0Oz/WiETESNJGrtUwScOg11JoovUE,iv:4/aXF1X40sjotA5D2R3IJ3OUm9WTlAF/m2dNnm2ujVk=,tag:lfKE0K9mpNeSk8tKs5anDA==,type:str]
ddns:
    cloudflare: ENC[AES256_GCM,data:kJvSf7TckkE7LnowSl3xj/rhmEpVLLM7Jt/LNhYPR5ngJyYX4et05A==,iv:RXsLhXtZZnipsKRGSgYHMquYDAhcXSV64GozIz20DHA=,tag:ZEyh1tw9TXop0egdJIYx+g==,type:str]
wireguard:
    private: ENC[AES256_GCM,data:68+Pv01ukQfAm5QFz45e0VaIj6mfVEXKYXhmiiqDcL4414Jy4ajeb2LM8Ds=,iv:iAUekLHmjDF35OlfXZNG7kzUbUmqxD6p9GtdN3rs9ZI=,tag:RKqmw46bPaDqF/Jws5YqOA==,type:str]
    preshare:
        phone: ENC[AES256_GCM,data:Giq/TKt/RzWcZMkIWdgqHzwWsZw9reVLQCcIMsUHIK5jvmlXw4LYWXXzIk0=,iv:Np2qld4ONomLU0L83fI2hDw+0UJx82KZtzAZZp6V2Ps=,tag:Dr2gxYTZGEjhPaEqwtVuZQ==,type:str]
        laptop: ENC[AES256_GCM,data:GFDZQjnqjxm5XaaujRZX7j9fXyEboLVDoRLhnTAA+nnUnDtQasgscFVP32A=,iv:rmPI+l93MiAifB+U/nMtbuk9FNDgw7GqWsI/nPqBXaM=,tag:f9bBpf9OsTN/37R+dlhGgA==,type:str]
vaultwarden: ENC[AES256_GCM,data:kDCo9t+cb3Jy3KTRqeeySB50eo4dWxjAjhe/rkRdY4sKpQ9aUSPzs7YWc5600rnw1q+y4fyVQ22Q5fi2zuBFNN9lvzsYUH+uVBGslVY3uuS1Ony+E4tmsfw6Pkhd8CNMv16ficL3htaoYNGBUGRqcSbPEPHAWBZRbAoVb5tdbhLBboXSMd1aeKCRNbIh7rkcEGTSTX9GDkPliQaHbmsSJJKrhPVYnzvUIPK1xWN0B3CNkDehmWx95GSKeS0dbyF5lTT4ULGY2EVZBe/k9/qzCUw5KDJeCze/3CcZR+5MOUQ+g7CsK90/,iv:R/5+vxKSTOi9pY8VaUw/DA3LUPZ911RyjHN2vX5+Kxs=,tag:m3auICpIbjVMMPZKSAaeIw==,type:str]
matrix:
    homeserver_key: ENC[AES256_GCM,data:A0Dkr8hEDHeWmc2aZa5lut+oWQcwlAXak3PMlEQ2zhXU5jG4bJ/FVkcbZRClVR/7vmc+UcSoTWSMoj5Zpg==,iv:8r+GbRmZbkczZyhKu8La2+2Jwdgu5288YQTGygPmtqU=,tag:KqRS26WRQ+Vuohj48Xwr1Q==,type:str]
    token: ENC[AES256_GCM,data:Tuuzd+G8a3mNpMAlBvcyU/dySgOT57XWgrQDncVfT0XEOiUWb+p1Ww==,iv:QTKtaz3s5jgox6obYTWv24CWlLJFlp7q7e/6cPF2h3A=,tag:hcDNK6PmLUlvolMuvRlkBA==,type:str]
sops:
    age:
        - recipient: age1zs4dcmqa2wxt3wx9f5mc9rekskz2cg39dvfv7jhwtef5uw5mpvgqgeurcl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbjJxOGdiL0VFTVp1SFk3
            WFVmbmxsTEhOdWZETzVsSGpMZlFxd2hlQ3kwCkUrb0JFWE80YTU0NHRnRVA5bGdz
            ZTJYdVo0WWlNN2NWYjNUd09aZHN6VVEKLS0tIFhvZEVHNnpVd3A2TXNWZ0VlbFhK
            U2lkdU9yOXJKSVJRU28wMnhzK1gxQzgK+Ocn2R7eCKkby1F77fIFfMDGjNfDamhH
            TJUlCW3D0TlwTTJuH8F+HN75QRSzZemkezamPQrO/qkKqS5dcSdCXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T23:40:25Z"
    mac: ENC[AES256_GCM,data:1UMBBs0GQehZjsZJVr8gDKZuRWmGDyKCTkC5RwwvZkyHGejfQR+ccxnF2KBjnco9A/gA8eV8UJchKm8pOXnKgPX472CmL0XjYzVg0LINerUp/dgIrGzKi6hKw80bnKEwVIUgN9K+5XyYepaewwWD02MErsykIS9VefZu595xZys=,iv:oBkI4KuEPFWu98SGwqJHf8uftn+xqNtYOC2AiT7BAh4=,tag:LVm+UNI4Ls7kY/3l23Sssw==,type:str]
    pgp:
        - created_at: "2025-03-16T12:33:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DhydhbbIyR5QSAQdA7xu3TmkuDTTxo6za7w1tkaHvLVw1YC2aQS4V+9RjKw0w
            nqGRNaBEAFkQcs7XKJ9N86BmkUdHcNKCcZbrS6kqbdwXNrp+V4/PzImdQE2TXZXu
            0lwBLUn2gJ6wLx1tF/d+bNgvYRPjJnCciYU/WSCbFTA5pA7gbu84xFjk2rRSYg0Y
            hdHysq5DSc8ri8l4zu1sYQOlxxE/ZJFTF69xLupnb6e4Js23bIOnKBLro5BJ5w==
            =2NyM
            -----END PGP MESSAGE-----
          fp: 676E7ED23DB572106D83619F8727616DB2324794
    unencrypted_suffix: _unencrypted
    version: 3.10.2
