ppp:
    wan: ENC[AES256_GCM,data:DkaAHMrIcK8Mc5OSxA7nQNr0Oz/WiETESNJGrtUwScOg11JoovUE,iv:4/aXF1X40sjotA5D2R3IJ3OUm9WTlAF/m2dNnm2ujVk=,tag:lfKE0K9mpNeSk8tKs5anDA==,type:str]
ddns:
    cloudflare: ENC[AES256_GCM,data:kJvSf7TckkE7LnowSl3xj/rhmEpVLLM7Jt/LNhYPR5ngJyYX4et05A==,iv:RXsLhXtZZnipsKRGSgYHMquYDAhcXSV64GozIz20DHA=,tag:ZEyh1tw9TXop0egdJIYx+g==,type:str]
wireguard:
    private: ENC[AES256_GCM,data:68+Pv01ukQfAm5QFz45e0VaIj6mfVEXKYXhmiiqDcL4414Jy4ajeb2LM8Ds=,iv:iAUekLHmjDF35OlfXZNG7kzUbUmqxD6p9GtdN3rs9ZI=,tag:RKqmw46bPaDqF/Jws5YqOA==,type:str]
    preshare:
        phone: ENC[AES256_GCM,data:Giq/TKt/RzWcZMkIWdgqHzwWsZw9reVLQCcIMsUHIK5jvmlXw4LYWXXzIk0=,iv:Np2qld4ONomLU0L83fI2hDw+0UJx82KZtzAZZp6V2Ps=,tag:Dr2gxYTZGEjhPaEqwtVuZQ==,type:str]
        laptop: ENC[AES256_GCM,data:GFDZQjnqjxm5XaaujRZX7j9fXyEboLVDoRLhnTAA+nnUnDtQasgscFVP32A=,iv:rmPI+l93MiAifB+U/nMtbuk9FNDgw7GqWsI/nPqBXaM=,tag:f9bBpf9OsTN/37R+dlhGgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs4dcmqa2wxt3wx9f5mc9rekskz2cg39dvfv7jhwtef5uw5mpvgqgeurcl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbjJxOGdiL0VFTVp1SFk3
            WFVmbmxsTEhOdWZETzVsSGpMZlFxd2hlQ3kwCkUrb0JFWE80YTU0NHRnRVA5bGdz
            ZTJYdVo0WWlNN2NWYjNUd09aZHN6VVEKLS0tIFhvZEVHNnpVd3A2TXNWZ0VlbFhK
            U2lkdU9yOXJKSVJRU28wMnhzK1gxQzgK+Ocn2R7eCKkby1F77fIFfMDGjNfDamhH
            TJUlCW3D0TlwTTJuH8F+HN75QRSzZemkezamPQrO/qkKqS5dcSdCXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T12:53:44Z"
    mac: ENC[AES256_GCM,data:iZIl13E3D9uk2tCMr9SGqheIDX6YA7NfbQtH+qRE3fmcxZf9VBepGW71t5oaYl05P1hyYkxn/rEHKlt/ZKQV4P5xolhQbQzCxMSHrUPQdRx+6z8QFeKhTPSw2rZn2C9rKcxk9RuuPR8uZZ3Ube7kxKh4NY33Dx1cnpp4harfWVc=,iv:MvaK+lj1k/Gi85B7MGMfa8cig2edko9ffXc2R2MCOUc=,tag:0I0ht2pzY6QVjPzHdyDDxQ==,type:str]
    pgp:
        - created_at: "2025-03-16T12:33:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DhydhbbIyR5QSAQdA7xu3TmkuDTTxo6za7w1tkaHvLVw1YC2aQS4V+9RjKw0w
            nqGRNaBEAFkQcs7XKJ9N86BmkUdHcNKCcZbrS6kqbdwXNrp+V4/PzImdQE2TXZXu
            0lwBLUn2gJ6wLx1tF/d+bNgvYRPjJnCciYU/WSCbFTA5pA7gbu84xFjk2rRSYg0Y
            hdHysq5DSc8ri8l4zu1sYQOlxxE/ZJFTF69xLupnb6e4Js23bIOnKBLro5BJ5w==
            =2NyM
            -----END PGP MESSAGE-----
          fp: 676E7ED23DB572106D83619F8727616DB2324794
    unencrypted_suffix: _unencrypted
    version: 3.9.4
