ppp:
    wan: ENC[AES256_GCM,data:DkaAHMrIcK8Mc5OSxA7nQNr0Oz/WiETESNJGrtUwScOg11JoovUE,iv:4/aXF1X40sjotA5D2R3IJ3OUm9WTlAF/m2dNnm2ujVk=,tag:lfKE0K9mpNeSk8tKs5anDA==,type:str]
ddns:
    cloudflare: ENC[AES256_GCM,data:kJvSf7TckkE7LnowSl3xj/rhmEpVLLM7Jt/LNhYPR5ngJyYX4et05A==,iv:RXsLhXtZZnipsKRGSgYHMquYDAhcXSV64GozIz20DHA=,tag:ZEyh1tw9TXop0egdJIYx+g==,type:str]
wireguard:
    private: ENC[AES256_GCM,data:68+Pv01ukQfAm5QFz45e0VaIj6mfVEXKYXhmiiqDcL4414Jy4ajeb2LM8Ds=,iv:iAUekLHmjDF35OlfXZNG7kzUbUmqxD6p9GtdN3rs9ZI=,tag:RKqmw46bPaDqF/Jws5YqOA==,type:str]
    preshare:
        phone: ENC[AES256_GCM,data:Giq/TKt/RzWcZMkIWdgqHzwWsZw9reVLQCcIMsUHIK5jvmlXw4LYWXXzIk0=,iv:Np2qld4ONomLU0L83fI2hDw+0UJx82KZtzAZZp6V2Ps=,tag:Dr2gxYTZGEjhPaEqwtVuZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hwaa8day3379dja06ppr5237l0nmt5r9zhwpm8hx03k06w4kqeq0m6jh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSG1aZkYwWjNaOXB1RmRU
            eldoR0dwSHVKZ0l5bnVxWDlNUDdjaUJPZFFrCnZlZFA1YXVaTGMyVlY2VHNFY09n
            MUsvbXY3WDZTU0pPM3lDemxDTHNxbk0KLS0tIDcyWldINjAxZEd3R3haTFpESzBU
            ZXBENCtlNll5bjB2ZkFHOHdzeWN4aG8KLfZvBpMX05W2UQEt1txgTl6Ec8WYVF0u
            rp4q2yvuP+nSg/XwuNBOltmeQ/OAKKg4gB3GJLgVqeGpo/7F2z2AaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T21:48:59Z"
    mac: ENC[AES256_GCM,data:AW3yd4be1S8v4C7XYdKrxYJnROC8nngMfT12NX7WUvQdR5r//X8hq0T1ybEhEWOiPk9zMPloAqfUClmNIpF2eeDjR14TolcWn/HpezlPAHPnYZq9ycSvcDao0njgYpJ/94vPkCqcQYkQ87r3lpe/SqtT8KgSGLWtbg1BfdkGQt0=,iv:cgwOzPK3aTFGRPt5FXbkj1bqMzM7UCdcCHZV4Tz0wy4=,tag:i2/zcCzsZcJiLwXoQJY/Hw==,type:str]
    pgp:
        - created_at: "2025-02-20T21:29:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DhydhbbIyR5QSAQdAxxDt5QSX0I/9n/I20956KScRGyyOK+LoLdRMqO9g3gYw
            NRS6ENIw/pKzP0AKXLwpDvj1cLqQ+EC5B6/4JRsyy563e8zyewgQc9Mh8tLG7P3T
            0l4BQE7m1ZQ2s0VXY4dlAEQXyMp319O7vvFCJpGsKyIZ9arDop4dbNkOBudDdR+a
            uChACDema3nHTgtJomLPAlTa9tAN9VO8xRvmPRhFgJE8fneRbtMY7aHAXVqa1X6y
            =v0yX
            -----END PGP MESSAGE-----
          fp: 676E7ED23DB572106D83619F8727616DB2324794
    unencrypted_suffix: _unencrypted
    version: 3.9.4
