ppp:
    wan: ENC[AES256_GCM,data:DkaAHMrIcK8Mc5OSxA7nQNr0Oz/WiETESNJGrtUwScOg11JoovUE,iv:4/aXF1X40sjotA5D2R3IJ3OUm9WTlAF/m2dNnm2ujVk=,tag:lfKE0K9mpNeSk8tKs5anDA==,type:str]
ddns:
    cloudflare: ENC[AES256_GCM,data:kJvSf7TckkE7LnowSl3xj/rhmEpVLLM7Jt/LNhYPR5ngJyYX4et05A==,iv:RXsLhXtZZnipsKRGSgYHMquYDAhcXSV64GozIz20DHA=,tag:ZEyh1tw9TXop0egdJIYx+g==,type:str]
wireguard:
    private: ENC[AES256_GCM,data:68+Pv01ukQfAm5QFz45e0VaIj6mfVEXKYXhmiiqDcL4414Jy4ajeb2LM8Ds=,iv:iAUekLHmjDF35OlfXZNG7kzUbUmqxD6p9GtdN3rs9ZI=,tag:RKqmw46bPaDqF/Jws5YqOA==,type:str]
    preshare:
        phone: ENC[AES256_GCM,data:Giq/TKt/RzWcZMkIWdgqHzwWsZw9reVLQCcIMsUHIK5jvmlXw4LYWXXzIk0=,iv:Np2qld4ONomLU0L83fI2hDw+0UJx82KZtzAZZp6V2Ps=,tag:Dr2gxYTZGEjhPaEqwtVuZQ==,type:str]
        laptop: ENC[AES256_GCM,data:GFDZQjnqjxm5XaaujRZX7j9fXyEboLVDoRLhnTAA+nnUnDtQasgscFVP32A=,iv:rmPI+l93MiAifB+U/nMtbuk9FNDgw7GqWsI/nPqBXaM=,tag:f9bBpf9OsTN/37R+dlhGgA==,type:str]
samba: ENC[AES256_GCM,data:jzqOlS/ZA5zEes389Ur7SqqN6iVhWTyA/P6dD9A7cpP9Pd+yZbul4psgoDw+euatfaJUCvxxRejarNh7+K4VdDGiCBIrjm43MFyHol3AA9Xy/XSbdPS0ijkm9/pV6Xs84fTxsCOZjbFZj5WFYklIAHla6eB+SEjokkyUE1Ab47GDX9u4IMq+uFdmU7SoKyl6ZyHmJwq4hieYKYPIWb6HBgZmm7mmg02k4hos4URChptNMFNZrwFe00gkVPg6rJdefQaca2KsZLwocx2iARgmMzSqkWrjZ1RgbFM=,iv:YDaFGgmBYtVbpMO3l13BixukmeXwMoD0LjNFsSHK3OE=,tag:wImlpNW5HtoB0tsTIxf5ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zs4dcmqa2wxt3wx9f5mc9rekskz2cg39dvfv7jhwtef5uw5mpvgqgeurcl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbjJxOGdiL0VFTVp1SFk3
            WFVmbmxsTEhOdWZETzVsSGpMZlFxd2hlQ3kwCkUrb0JFWE80YTU0NHRnRVA5bGdz
            ZTJYdVo0WWlNN2NWYjNUd09aZHN6VVEKLS0tIFhvZEVHNnpVd3A2TXNWZ0VlbFhK
            U2lkdU9yOXJKSVJRU28wMnhzK1gxQzgK+Ocn2R7eCKkby1F77fIFfMDGjNfDamhH
            TJUlCW3D0TlwTTJuH8F+HN75QRSzZemkezamPQrO/qkKqS5dcSdCXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T01:11:46Z"
    mac: ENC[AES256_GCM,data:8C3pleicaAS1Ixq20MC/OwCd1Lg0IZhwOVVCtGFyeGDgyUYdBbCXEhOioiEitF/M33QzVLSwY2YjGTEYnTY/OK4leHeWGW+aNAmFYcX7NrVrVOJNX284vVvNp/kPxCfqCrNudiJuB0ezbOUCchWbrHsCiQynINP6pLEgp2dywFY=,iv:kkmRcs58JVU0iZju7v23sZXRChHbvrsFVu65hw+Vnrc=,tag:hZwUTHvmV9M2FZYKrJjjOw==,type:str]
    pgp:
        - created_at: "2025-03-16T12:33:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DhydhbbIyR5QSAQdA7xu3TmkuDTTxo6za7w1tkaHvLVw1YC2aQS4V+9RjKw0w
            nqGRNaBEAFkQcs7XKJ9N86BmkUdHcNKCcZbrS6kqbdwXNrp+V4/PzImdQE2TXZXu
            0lwBLUn2gJ6wLx1tF/d+bNgvYRPjJnCciYU/WSCbFTA5pA7gbu84xFjk2rRSYg0Y
            hdHysq5DSc8ri8l4zu1sYQOlxxE/ZJFTF69xLupnb6e4Js23bIOnKBLro5BJ5w==
            =2NyM
            -----END PGP MESSAGE-----
          fp: 676E7ED23DB572106D83619F8727616DB2324794
    unencrypted_suffix: _unencrypted
    version: 3.9.4
